# Site settings
title: rkayg
email: rahulkartgupta@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rkayg.com" # the base hostname & protocol for your site
twitter_username: rahulk_g
github_username:  rahulkgupta
